POST http://localhost:7654/api/v1/users
Content-Type: application/json

{
    "username": "TestUser",
    "pwd": "QWer12#%i",
    "email": "some.email@email.com"
}


###
GET http://localhost:7654/api/v1/users/30567





###
POST http://localhost:7654/api/v1/books
Content-Type: application/json

{
    "author": "J.K rowling",
    "title": "Some Harry Potter Book",
    "release_year": 2000,
    "isbn": 1234567891234
}

###
GET http://localhost:7654/api/v1/books/2603